### ISSUE TITLE
Namespace GstRtspServer not available

### ISSUE THREAD

**Issue by weilan97** [Enne2/PyGObject-GstRtspServer#1]
Hi,
I already installed the required packages. But I got the error: ValueError: Namespace GstRtspServer not available.
How to fix it?

**Comment by Enne2** [comment]
Hi mate!
Are you sure you have installed gir1.2-gst-rtsp-server-1.0 package?
What's your OS distro?

**Comment by weilan97** [comment]
I am pretty sure I installed gir1.2-gst-rtsp-server-1.0 package and all other gstreamer packages. 
I am using Ubuntu 18.04.
Thanks!

**Comment by Enne2** [comment]
Try a newer distro, probably gstreamer's python wrapper in Ubuntu 18.04 was still incomplete.
